### ISSUE TITLE
BUG: Interpolation bias or affine adjustment issue when reorienting LAS image

### ISSUE THREAD

**Issue by pauldmccarthy** [neuroanatomy/reorient#4]
## Thank you for your feedback.

Hi again @r03ert0 and @katjaq :) I _think_ I've found a slight issue with the way that the `reorient` tool resamples an image, or constructs the voxel-to-world affine, when reorienting an image with LAS voxel storage order (the MNI152 2mm standard template which comes as part of FSL has this voxel storage order).

The `reorient` tool appears to be invariant to the voxel-storage order of loaded images (i.e. how the voxel coordinate system axes map to the LR/AP/IS anatomical coordinate system axes), and seems to always output images with a RAS voxel storage order. Overall I think this is a very good thing, as images with non LAS/RAS voxel storage orders are a common source of registration failure, so forcing all output images to have a consistent and standard storage order will help to prevent such failures.

However, there appears to be an issue in the interpolation/resampling implemented within `reorient` when working with an image which originally has LAS voxel storage order (i.e. where a left-right flip is encoded into the voxel-to-world affine matrix).  Steps to reproduce are outlined below.

### Current behaviour

1. Load an image with LAS voxel storage order into `reorient` - [here is an example](https://github.com/neuroanatomy/reorient/files/5322132/MNI152_T1_2mm_downsampled.nii.gz). It is the MNI152 2mm standard template from FSL, downsampled by a factor of ~2, to make the effect clearer.
2. Use the *Select* tool to crop the image. I cropped the image using [this selection box](https://github.com/neuroanatomy/reorient/files/5322135/selection_mni.txt) (this file has had a new line added as per #3)
3. Save the result out to disk - [here is what I get](https://github.com/neuroanatomy/reorient/files/5322137/reoriented.nii.gz)
4. View the results in an image viewer which aligns images according to their voxel-to-world affine (e.g. FSLeyes). 

Here is a screencast demonstrating the result in FSLeyes (apologies for the clunkiness). I have the original MNI152 2mm template, the downsampled version, and then the re-oriented version on top:

![screencast](https://user-images.githubusercontent.com/236128/94999293-56963680-05b0-11eb-859e-d3f31512ebd2.gif) 

### Version information (for bug reports)

* **Browser + version**: Firefox 80.0.1
* **Your OS + version**: Ubuntu 18.04

**Comment by r03ert0** [comment]
I think it's fixed now : )

There were several things. We created a series of very small nifti files, with different matrices, voxel shape, etc. I'll post some examples.

The display of the crop-box was not accurate to the pixel, the image display was using nearest neighbour interpolation only, and the size of the image was also not pixel-accurate.

Here's the result on the same downsampled image:

![out](https://user-images.githubusercontent.com/2310732/96442922-28e5fa00-120c-11eb-9543-a230d0ba1588.gif)

**Comment by r03ert0** [comment]
Another thing that seemed to contribute to the bias was the volume translation. Volumes resampled using reorient had by default a translation that was an integer number of voxel dimensions. In FSLEyes, moving to the (0,0,0) coordinate, for example, will put the axis cross in the middle of the voxel. The source downsampled image (MNI152...) had a different displacement. Because voxels were so big, this contributed to the "shift" effect. Here's a zoom on the previous GIF showing this:
![voxel_shift](https://user-images.githubusercontent.com/2310732/96443655-3c459500-120d-11eb-9e81-11034a2a355b.gif)

Additionally, the GIF shows the isotropic resampling of reorient compared with the original anisotropic voxels.

**Comment by r03ert0** [comment]
If the voxels of the source MNI152 volume are made to be isotropic and the translation rounded to voxel size in world space (just by changing the affine matrix), the position of the voxels and their values match perfectly, showing that the code works correctly now :)
![perfect](https://user-images.githubusercontent.com/2310732/96444391-7b281a80-120e-11eb-9ef6-81d7c72eb7e5.gif)
(I used the "copper" colourmap, otherwise, there's no difference)

**Comment by r03ert0** [comment]
One more test: a small volume with 2*3*4 voxels is associated to 6 different affine matrices, representing different encodings for the voxels. For each volume the image shows that the rendering is the same as in FSLEyes (L/R radiological in FSLEyes, but neurological in Reorient). The corresponding affine matrices are displayed in each subplot.

![orientation 001](https://user-images.githubusercontent.com/2310732/96468107-fb10ad80-122b-11eb-98ce-f492b1c88e18.jpeg)

**Comment by r03ert0** [comment]
This image shows that the crop result is well aligned with the original image for all 6 affine matrices. Each time the crop-box is the same. In the cases where the crop-box includes voxels outside the original nifti volume, the space is filled with 0. The cropped result is displayed using the copper colourmap (otherwise, the grey levels are exactly the same).

![orientation 002](https://user-images.githubusercontent.com/2310732/96468430-63f82580-122c-11eb-84ce-2749e064a54f.jpeg)

**Comment by r03ert0** [comment]
We have more test images, in particular, testing the interpolation with anisotropic voxels, but the results are similar to those from the comment 4h ago. I'll close the issue : )
Thank you @pauldmccarthy for pointing it out!

**Comment by pauldmccarthy** [comment]
Amazing work, sorry to have caused you all this hassle!

**Comment by r03ert0** [comment]
on the contrary! thank you so much for accepting to review our code 🙏
