### ISSUE TITLE
When crop box not explicitly set, don't crop

### ISSUE THREAD

**Issue by sneakers-the-rat** [neuroanatomy/reorient#5]
### Current behaviour

* If this is a bug, please explain how to reproduce the problem - not a bug per se, improvement in intuitive behavior let's call it.
    * Which tools did you use in which sequence? - reorienting, cropping, saving.
    * Does the error concern the online display/ functionality or the downloaded result? - downloaded result
    * What is the type and resolution of your data? (Can you provide a link to your data?) - the 1GB 200um downsampled nifti from here: https://datadryad.org/stash/dataset/doi:10.5061/dryad.119f80q
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools.

When I translate and rotate a brain and then save the image without explicitly setting a cropping box, the resulting file is cropped with the small crop box that is invisibly set by default.

### Expected behaviour

The default/initial crop box should be the whole image (ie. no crop) <3.

### Version information (for bug reports)

* **Browser + version**: Firefox 81.0.1
* **Your OS + version**: macOS 10.15.6

**Comment by r03ert0** [comment]
It's not possible to decide automatically on an image size. We need to define a box that would be large enough to contain the original volume and its potential rotations. But if the box is too large, we wouldn't be able to see the details of the image.

There's two problems:

One is that MRI images have very often wrong origins. The most frequently used MRI viewers automatically centre the data, which obfuscates the issue. This is not a problem in most cases. Here, however, because our aim is to edit the translation and rotation values, the real translation has to be shown. If the origin is too far off, the user will need to look at the translation part of the affine matrix, and try to bring those numbers closer to (0,0,0) to at least start to see the image.

Then, the box needs to be able to hold potential rotations. Human MRI data comes often rather well aligned (people are after all lying in a very tight tunnel that leaves little possibilities for fancy rotations). However, non-human data, ex-vivo material in particular, is often free floating in a jar. The orientation can be completely arbitrary.

We decided on a heuristic. We find the largest dimension of the volume (accounting for anisotropic voxel sizes) and multiply that value by 1.5. We use that as the size of our box. The image illustrates our thinking:

<img width="741" alt="orientation_heuristic" src="https://user-images.githubusercontent.com/2310732/96561018-5475ec80-12bf-11eb-9603-f8b697cad012.png">

We focus on a single rotation (i.e., a 2D instead of a 3D box). The worst case scenario for a rotation is if we wanted to rotate a square 45º, where our automatic box would need to fit a dimension that's sqrt(2) of the square's side. For the worst rotation in a rectangle the increase in size is smaller than if it were a square. We could think of a cube and use sqrt(3). Our scaling value of 1.5 is somewhere in the middle.

Although we want the size of the box to be as tight as possible, it will always be too large. The user *has* to adapt it manually.

To resolve the issue of the unexpected crop box, we decided to add a warning. If the user clicks "Save Nifti" but the size of the crop box is still the default size, we display the following confirmation dialog:

<img width="460" alt="box_heuristic_dialog" src="https://user-images.githubusercontent.com/2310732/96562182-c438a700-12c0-11eb-8d56-ac7f4ebac284.png">

With that we should be sure that the user is aware of the necessity of adjusting the selection box before saving.

Finally, if the user is only interested in changing the original affine matrix of the volume, there is no need for saving a new resampled nifti file, and just the matrix text file should suffice.
