### ISSUE TITLE
Large files load indefinitely

### ISSUE THREAD

**Issue by sneakers-the-rat** [neuroanatomy/reorient#7]
### Current behaviour

Tried to test program using this 8GB scan: https://datadryad.org/stash/downloads/file_stream/223921 , let the page sit for ~40m while i was working on review, remained hung on 'uploading'

* If this is a bug, please explain how to reproduce the problem 
    * Which tools did you use in which sequence? - loading
    * Does the error concern the online display/ functionality or the downloaded result?  - display/functionality
    * What is the type and resolution of your data? (Can you provide a link to your data?) - https://datadryad.org/stash/downloads/file_stream/223921
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools. - no message in console

### Expected behaviour

would love to have a progress bar or some indication that the loading is still happening, or else an error message indicating that it failed!

### Version information (for bug reports)

* **Browser + version**: Firefox 81.0.1
* **Your OS + version**: macOS 10.15.6

**Comment by r03ert0** [comment]
Thank you for the issue report @sneakers-the-rat!
We improved the feedback given when loading a file. We now display a message indicating that an uploading is going on. In the case of the file you were trying, it failed because it's extremely large for MRI standards. In case of error, we now display a message indicating to either try again or to report a bug. We also check for file size, and provide an indication in case the file is >200MB (which is rarely the case, most brain MRI files are <100MB).

<img width="958" alt="loading-1" src="https://user-images.githubusercontent.com/2310732/96503675-f06a0e80-1253-11eb-8e5a-e162ac865f31.png">
<img width="958" alt="loading-2" src="https://user-images.githubusercontent.com/2310732/96503718-f6f88600-1253-11eb-9a00-ffe9dce64f57.png">
<img width="958" alt="loading-3" src="https://user-images.githubusercontent.com/2310732/96503731-fd86fd80-1253-11eb-91ea-98d3319b5e44.png">
